version: "3.8"

services:
  backend:
    build: .
    ports:
      - "${API_PORT}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run start:dev"
